Untabify, remove trailing whitespace, indentation fixes.

diff --git a/build-debian-cloud b/build-debian-cloud
--- a/build-debian-cloud
+++ b/build-debian-cloud
@@ -6,10 +6,10 @@ set -e
 # Rember various paths
 scriptdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 if [ ! -d "$scriptdir/tasks" ]; then
-	scriptdir='/usr/share/build-debian-cloud'
-	if [ ! -d "$scriptdir/tasks" ]; then
-		die "Unable to locate tasks folder."
-	fi
+    scriptdir='/usr/share/build-debian-cloud'
+    if [ ! -d "$scriptdir/tasks" ]; then
+        die "Unable to locate tasks folder."
+    fi
 fi
 originaldir=$(pwd)
 
@@ -58,53 +58,53 @@ platform=$1
 
 # Figure out which pvGrub kernel ID we need
 case $platform in
-	ec2|gce) shift ;;
-	*)       printf -- "$platform_help"; exit 0  ;;
+    ec2|gce) shift ;;
+    *)       printf -- "$platform_help"; exit 0  ;;
 esac
 
 source $platform
 
 # Check if the chosen fs is on we can handle.
 case $filesystem in
-	xfs)  ;;
-	ext2) ;;
-	ext3) ;;
-	ext4) ;;
-	*)    die "The filesystem $filesystem was not recognized." \
-	          "Valid filesystems are ext[2-4] and xfs"      ;;
+    xfs)  ;;
+    ext2) ;;
+    ext3) ;;
+    ext4) ;;
+    *)    die "The filesystem $filesystem was not recognized." \
+        "Valid filesystems are ext[2-4] and xfs"      ;;
 esac
 
 # Put all tasks in the tasks folder into an array. Tolerate the absence
 # of some possible directories.
 directories=`ls -d $scriptdir/tasks $scriptdir/tasks/$codename \
-	$scriptdir/tasks/$platform $scriptdir/tasks/$platform/$codename \
-	2>/dev/null || true`
+    $scriptdir/tasks/$platform $scriptdir/tasks/$platform/$codename \
+    2>/dev/null || true`
 tasklist=`find $directories \
-	-maxdepth 1 -type f -name '[0-9][0-9]-*' \
-	-printf '%p\t%f\n' | sort -k 2 | awk '{print $1}'`
+    -maxdepth 1 -type f -name '[0-9][0-9]-*' \
+    -printf '%p\t%f\n' | sort -k 2 | awk '{print $1}'`
 tasks=()
 for task in $tasklist; do
-	if $(contains_basename `basename $task` tasks[@]); then
-		die "The task $task has a naming conflict with an existing task." "Please rename the file."
-	fi
-	tasks+=($task)
+    if $(contains_basename `basename $task` tasks[@]); then
+        die "The task $task has a naming conflict with an existing task." "Please rename the file."
+    fi
+    tasks+=($task)
 done
 
 # Invoke plugins so that they may reorder and add tasks
 for plugin in "${plugins[@]}"; do
-	[ -e $plugin ] || die "The plugin file $plugin does not exist."
-	# Get the directory of the current plugin.
-	# This way the plugins don't have to figure it out for themselves.
-	plugindir=`dirname $plugin`
-	source $plugin
+    [ -e $plugin ] || die "The plugin file $plugin does not exist."
+    # Get the directory of the current plugin.
+    # This way the plugins don't have to figure it out for themselves.
+    plugindir=`dirname $plugin`
+    source $plugin
 done
 unset plugindir
 
 # Source all tasks in the right order
 for task in ${tasks[*]}; do
-	[ -e $task ] || die "The task $task does not exist."
-	log "Run task: `basename $task`"
-	taskdir=`dirname $task`
-	source $task || true
+    [ -e $task ] || die "The task $task does not exist."
+    log "Run task: `basename $task`"
+    taskdir=`dirname $task`
+    source $task || true
 done
 unset taskdir
diff --git a/tasks/14-bootstrap b/tasks/14-bootstrap
--- a/tasks/14-bootstrap
+++ b/tasks/14-bootstrap
@@ -21,26 +21,26 @@ tarball="$tarballdir/bootstrap-${args_hash:0:7}.tar"
 
 include_param=""
 if [[ $include != "" ]]; then
-	include_param="--include=$include"
+    include_param="--include=$include"
 fi
 
 exclude_param=""
 if [[ $exclude != "" ]]; then
-	exclude_param="--exclude=$exclude"
+    exclude_param="--exclude=$exclude"
 fi
 
 # When testing, some bootstraps can fail, instead of re-downloading it all
 # we create a tarball containing all the necessary things for bootstrapping
 if [ ! -e "$tarball" ]; then
-	log "Creating the bootstrap tarball"
-	debootstrap --arch $arch --make-tarball=$tarball \
-		${include_param} ${exclude_param} \
-		$codename $imagedir $bootstrap_mirror | spin
-	[ $PIPESTATUS == 1 ] || die "Creating bootstrap tarball failed!"
+    log "Creating the bootstrap tarball"
+    debootstrap --arch $arch --make-tarball=$tarball \
+        ${include_param} ${exclude_param} \
+        $codename $imagedir $bootstrap_mirror | spin
+    [ $PIPESTATUS == 1 ] || die "Creating bootstrap tarball failed!"
 fi
 
 log "Bootstrapping"
 debootstrap --arch $arch --unpack-tarball=$tarball \
-	${include_param} ${exclude_param} \
-	$codename $imagedir $bootstrap_mirror | spin
+    ${include_param} ${exclude_param} \
+    $codename $imagedir $bootstrap_mirror | spin
 [ $PIPESTATUS == 0 ] || die "Bootstrapping failed!"
diff --git a/tasks/ec2/05-install-euca2ools b/tasks/ec2/05-install-euca2ools
--- a/tasks/ec2/05-install-euca2ools
+++ b/tasks/ec2/05-install-euca2ools
@@ -1,26 +1,27 @@
 #!/bin/bash
+#
+# Make sure euca2ools is installed.
 
-# We use euca2ools to communicate with AWS
 # The package in squeeze is v 1.2, which does not support EBS images
 # So we install 1.3 from source instead
 if [ ! -d $scriptdir/euca2ools ]; then
-	wget -qO $scriptdir/euca2ools-1.3.2.tar.gz https://github.com/eucalyptus/euca2ools/archive/1.3.2.tar.gz
-	tar zxf $scriptdir/euca2ools-1.3.2.tar.gz
+    wget -qO $scriptdir/euca2ools-1.3.2.tar.gz https://github.com/eucalyptus/euca2ools/archive/1.3.2.tar.gz
+    tar zxf $scriptdir/euca2ools-1.3.2.tar.gz
 fi
 
 function install_euca2ools {
-	# We want to fail if make fails, so don't start a subshell with ()
-	# Remember the old dir
-	local orig_pwd=$(pwd)
-	cd euca2ools-1.3.2
-	make | spin
-	[ $PIPESTATUS == 0 ] || die "Bootstrapping failed!"
-	cd $orig_pwd
+    # We want to fail if make fails, so don't start a subshell with ()
+    # Remember the old dir
+    local orig_pwd=$(pwd)
+    cd euca2ools-1.3.2
+    make | spin
+    [ $PIPESTATUS == 0 ] || die "Bootstrapping failed!"
+    cd $orig_pwd
 }
 
 # make the euca2ools if they are not installed or the version is wrong
 if ! command -v euca-version > /dev/null 2>&1; then
-	install_euca2ools
+    install_euca2ools
 elif [[ ! "`euca-version`" =~ euca2ools\ 1.3.* ]]; then
-	install_euca2ools
+    install_euca2ools
 fi
