Have envcheck ensure s3mcmd is at least 1.6.0

diff --git a/envcheck b/envcheck
--- a/envcheck
+++ b/envcheck
@@ -9,6 +9,7 @@ declare -i move_s3_path=2
 declare -i partitioning=2
 declare -i python=1
 declare -i grant_launch_permission=1
+declare s3cmd_ver
 
 declare -r s3cfg="${HOME}/.s3cfg"
 
@@ -65,6 +66,13 @@ else
     echo "     ok AWS_CREDENTIAL_FILE=${AWS_CREDENTIAL_FILE}"
 fi
 
+# Check for bc support.
+if ! command -v bc 1>/dev/null
+then
+    echo "bc is not installed. Cannot complete checks."
+    exit 1
+fi
+
 # Check s3cmd support.
 if ! command -v s3cmd 1>/dev/null
 then
@@ -72,6 +80,13 @@ then
     move_s3_path=1
 elif [ -f "${s3cfg}" ]
 then
+    s3cmd_ver="$(s3cmd  --version | \
+        sed 's/^s3cmd\ version\ \([0-9]\+\.[0-9]\+\)\..*$/\1/')"
+    if [ "$(echo "${s3cmd_ver} < 1.6" | bc)" -eq 1 ]
+    then
+        echo "s3cmd version unsupported. Please upgrade to >= 1.6"
+        move_s3_path=1
+    fi
     if [ -n "${AWS_ACCESS_KEY}" ]
     then
         if ! grep -iq "^access_key\s*=\s*${AWS_ACCESS_KEY}\s*$" "${s3cfg}"
