Make 39-networking-interfaces not exclusive to jessie
Modified contents merged into 39-networking.

diff --git a/tasks/39-networking b/tasks/39-networking
--- a/tasks/39-networking
+++ b/tasks/39-networking
@@ -8,3 +8,17 @@ rm -f "${imagedir}/etc/resolv.conf"
 # Set /etc/hostname to localhost to avoid a "the specified hostname is
 # invalid" warning on boot.
 echo localhost > "${imagedir}/etc/hostname"
+
+# In Jessie and newer, interfaces contains the line: source-directory
+# /etc/network/interfaces.d.  and (aside from comments) nothing else.
+#
+# Note the dhcpcd daemon will fail to start if eth0 is already
+# defined.
+if ! grep -q '^auto lo\ *$' "${imagedir}/etc/network/interfaces"
+then
+	cat > "${imagedir}/etc/network/interfaces.d/lo" <<EOF
+# The loopback network interface
+auto lo
+iface lo inet loopback
+EOF
+fi
